// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bmp_grapher.proto

#include "advanced_cxx/bmp_grapher.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_bmp_5fgrapher_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_BmpGrapher_bmp_5fgrapher_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_bmp_5fgrapher_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_MandelbrotConfig_bmp_5fgrapher_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_bmp_5fgrapher_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_MandelbrotConfig_MandelbrotRunArgs_bmp_5fgrapher_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_bmp_5fgrapher_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs_bmp_5fgrapher_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_bmp_5fgrapher_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RGB_bmp_5fgrapher_2eproto;
namespace bmp_grapher_proto {
class RGBDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RGB> _instance;
} _RGB_default_instance_;
class MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs> _instance;
} _MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs_default_instance_;
class MandelbrotConfig_MandelbrotRunArgsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MandelbrotConfig_MandelbrotRunArgs> _instance;
  const ::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs* single_color_scheme_args_;
} _MandelbrotConfig_MandelbrotRunArgs_default_instance_;
class MandelbrotConfigDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MandelbrotConfig> _instance;
} _MandelbrotConfig_default_instance_;
class BmpGrapherDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<BmpGrapher> _instance;
  const ::bmp_grapher_proto::MandelbrotConfig* mandelbrot_config_;
} _BmpGrapher_default_instance_;
class BmpGrapherFactoryDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<BmpGrapherFactory> _instance;
} _BmpGrapherFactory_default_instance_;
}  // namespace bmp_grapher_proto
static void InitDefaultsscc_info_BmpGrapher_bmp_5fgrapher_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bmp_grapher_proto::_BmpGrapher_default_instance_;
    new (ptr) ::bmp_grapher_proto::BmpGrapher();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bmp_grapher_proto::BmpGrapher::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_BmpGrapher_bmp_5fgrapher_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_BmpGrapher_bmp_5fgrapher_2eproto}, {
      &scc_info_MandelbrotConfig_bmp_5fgrapher_2eproto.base,}};

static void InitDefaultsscc_info_BmpGrapherFactory_bmp_5fgrapher_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bmp_grapher_proto::_BmpGrapherFactory_default_instance_;
    new (ptr) ::bmp_grapher_proto::BmpGrapherFactory();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bmp_grapher_proto::BmpGrapherFactory::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_BmpGrapherFactory_bmp_5fgrapher_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_BmpGrapherFactory_bmp_5fgrapher_2eproto}, {
      &scc_info_BmpGrapher_bmp_5fgrapher_2eproto.base,}};

static void InitDefaultsscc_info_MandelbrotConfig_bmp_5fgrapher_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bmp_grapher_proto::_MandelbrotConfig_default_instance_;
    new (ptr) ::bmp_grapher_proto::MandelbrotConfig();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bmp_grapher_proto::MandelbrotConfig::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_MandelbrotConfig_bmp_5fgrapher_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_MandelbrotConfig_bmp_5fgrapher_2eproto}, {
      &scc_info_MandelbrotConfig_MandelbrotRunArgs_bmp_5fgrapher_2eproto.base,}};

static void InitDefaultsscc_info_MandelbrotConfig_MandelbrotRunArgs_bmp_5fgrapher_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bmp_grapher_proto::_MandelbrotConfig_MandelbrotRunArgs_default_instance_;
    new (ptr) ::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_MandelbrotConfig_MandelbrotRunArgs_bmp_5fgrapher_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_MandelbrotConfig_MandelbrotRunArgs_bmp_5fgrapher_2eproto}, {
      &scc_info_MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs_bmp_5fgrapher_2eproto.base,}};

static void InitDefaultsscc_info_MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs_bmp_5fgrapher_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bmp_grapher_proto::_MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs_default_instance_;
    new (ptr) ::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs_bmp_5fgrapher_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs_bmp_5fgrapher_2eproto}, {
      &scc_info_RGB_bmp_5fgrapher_2eproto.base,}};

static void InitDefaultsscc_info_RGB_bmp_5fgrapher_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bmp_grapher_proto::_RGB_default_instance_;
    new (ptr) ::bmp_grapher_proto::RGB();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bmp_grapher_proto::RGB::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RGB_bmp_5fgrapher_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_RGB_bmp_5fgrapher_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_bmp_5fgrapher_2eproto[6];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_bmp_5fgrapher_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_bmp_5fgrapher_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_bmp_5fgrapher_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::RGB, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::RGB, red_),
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::RGB, green_),
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::RGB, blue_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs, mandelbrot_color_),
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs, base_color_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs, out_filename_),
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs, color_scheme_),
  offsetof(::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgsDefaultTypeInternal, single_color_scheme_args_),
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs, color_scheme_args_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::MandelbrotConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::MandelbrotConfig, max_iterations_),
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::MandelbrotConfig, run_args_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::BmpGrapher, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::BmpGrapher, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::BmpGrapher, x_center_),
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::BmpGrapher, y_center_),
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::BmpGrapher, x_domain_width_),
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::BmpGrapher, pixel_width_),
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::BmpGrapher, pixel_height_),
  offsetof(::bmp_grapher_proto::BmpGrapherDefaultTypeInternal, mandelbrot_config_),
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::BmpGrapher, bmp_grapher_config_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::BmpGrapherFactory, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::bmp_grapher_proto::BmpGrapherFactory, bitmaps_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::bmp_grapher_proto::RGB)},
  { 8, -1, sizeof(::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs)},
  { 15, -1, sizeof(::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs)},
  { 24, -1, sizeof(::bmp_grapher_proto::MandelbrotConfig)},
  { 31, -1, sizeof(::bmp_grapher_proto::BmpGrapher)},
  { 43, -1, sizeof(::bmp_grapher_proto::BmpGrapherFactory)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bmp_grapher_proto::_RGB_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bmp_grapher_proto::_MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bmp_grapher_proto::_MandelbrotConfig_MandelbrotRunArgs_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bmp_grapher_proto::_MandelbrotConfig_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bmp_grapher_proto::_BmpGrapher_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::bmp_grapher_proto::_BmpGrapherFactory_default_instance_),
};

const char descriptor_table_protodef_bmp_5fgrapher_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021bmp_grapher.proto\022\021bmp_grapher_proto\"/"
  "\n\003RGB\022\013\n\003red\030\001 \001(\005\022\r\n\005green\030\002 \001(\005\022\014\n\004blu"
  "e\030\003 \001(\005\"\244\004\n\020MandelbrotConfig\022\026\n\016max_iter"
  "ations\030\001 \001(\005\022G\n\010run_args\030\002 \003(\01325.bmp_gra"
  "pher_proto.MandelbrotConfig.MandelbrotRu"
  "nArgs\032\256\003\n\021MandelbrotRunArgs\022\024\n\014out_filen"
  "ame\030\001 \001(\t\022a\n\014color_scheme\030\002 \001(\0162K.bmp_gr"
  "apher_proto.MandelbrotConfig.MandelbrotR"
  "unArgs.MandelbrotColorScheme\022o\n\030single_c"
  "olor_scheme_args\030\003 \001(\0132K.bmp_grapher_pro"
  "to.MandelbrotConfig.MandelbrotRunArgs.Si"
  "ngleColorSchemeArgsH\000\032u\n\025SingleColorSche"
  "meArgs\0220\n\020mandelbrot_color\030\001 \001(\0132\026.bmp_g"
  "rapher_proto.RGB\022*\n\nbase_color\030\002 \001(\0132\026.b"
  "mp_grapher_proto.RGB\"#\n\025MandelbrotColorS"
  "cheme\022\n\n\006SINGLE\020\000B\023\n\021color_scheme_args\"\313"
  "\001\n\nBmpGrapher\022\020\n\010x_center\030\001 \001(\001\022\020\n\010y_cen"
  "ter\030\002 \001(\001\022\026\n\016x_domain_width\030\003 \001(\001\022\023\n\013pix"
  "el_width\030\004 \001(\005\022\024\n\014pixel_height\030\005 \001(\005\022@\n\021"
  "mandelbrot_config\030\006 \001(\0132#.bmp_grapher_pr"
  "oto.MandelbrotConfigH\000B\024\n\022bmp_grapher_co"
  "nfig\"C\n\021BmpGrapherFactory\022.\n\007bitmaps\030\001 \003"
  "(\0132\035.bmp_grapher_proto.BmpGrapherb\006proto"
  "3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_bmp_5fgrapher_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_bmp_5fgrapher_2eproto_sccs[6] = {
  &scc_info_BmpGrapher_bmp_5fgrapher_2eproto.base,
  &scc_info_BmpGrapherFactory_bmp_5fgrapher_2eproto.base,
  &scc_info_MandelbrotConfig_bmp_5fgrapher_2eproto.base,
  &scc_info_MandelbrotConfig_MandelbrotRunArgs_bmp_5fgrapher_2eproto.base,
  &scc_info_MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs_bmp_5fgrapher_2eproto.base,
  &scc_info_RGB_bmp_5fgrapher_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_bmp_5fgrapher_2eproto_once;
static bool descriptor_table_bmp_5fgrapher_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_bmp_5fgrapher_2eproto = {
  &descriptor_table_bmp_5fgrapher_2eproto_initialized, descriptor_table_protodef_bmp_5fgrapher_2eproto, "bmp_grapher.proto", 921,
  &descriptor_table_bmp_5fgrapher_2eproto_once, descriptor_table_bmp_5fgrapher_2eproto_sccs, descriptor_table_bmp_5fgrapher_2eproto_deps, 6, 0,
  schemas, file_default_instances, TableStruct_bmp_5fgrapher_2eproto::offsets,
  file_level_metadata_bmp_5fgrapher_2eproto, 6, file_level_enum_descriptors_bmp_5fgrapher_2eproto, file_level_service_descriptors_bmp_5fgrapher_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_bmp_5fgrapher_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_bmp_5fgrapher_2eproto)), true);
namespace bmp_grapher_proto {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MandelbrotConfig_MandelbrotRunArgs_MandelbrotColorScheme_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_bmp_5fgrapher_2eproto);
  return file_level_enum_descriptors_bmp_5fgrapher_2eproto[0];
}
bool MandelbrotConfig_MandelbrotRunArgs_MandelbrotColorScheme_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr MandelbrotConfig_MandelbrotRunArgs_MandelbrotColorScheme MandelbrotConfig_MandelbrotRunArgs::SINGLE;
constexpr MandelbrotConfig_MandelbrotRunArgs_MandelbrotColorScheme MandelbrotConfig_MandelbrotRunArgs::MandelbrotColorScheme_MIN;
constexpr MandelbrotConfig_MandelbrotRunArgs_MandelbrotColorScheme MandelbrotConfig_MandelbrotRunArgs::MandelbrotColorScheme_MAX;
constexpr int MandelbrotConfig_MandelbrotRunArgs::MandelbrotColorScheme_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

void RGB::InitAsDefaultInstance() {
}
class RGB::_Internal {
 public:
};

RGB::RGB()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bmp_grapher_proto.RGB)
}
RGB::RGB(const RGB& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&red_, &from.red_,
    static_cast<size_t>(reinterpret_cast<char*>(&blue_) -
    reinterpret_cast<char*>(&red_)) + sizeof(blue_));
  // @@protoc_insertion_point(copy_constructor:bmp_grapher_proto.RGB)
}

void RGB::SharedCtor() {
  ::memset(&red_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&blue_) -
      reinterpret_cast<char*>(&red_)) + sizeof(blue_));
}

RGB::~RGB() {
  // @@protoc_insertion_point(destructor:bmp_grapher_proto.RGB)
  SharedDtor();
}

void RGB::SharedDtor() {
}

void RGB::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RGB& RGB::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RGB_bmp_5fgrapher_2eproto.base);
  return *internal_default_instance();
}


void RGB::Clear() {
// @@protoc_insertion_point(message_clear_start:bmp_grapher_proto.RGB)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&red_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&blue_) -
      reinterpret_cast<char*>(&red_)) + sizeof(blue_));
  _internal_metadata_.Clear();
}

const char* RGB::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 red = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          red_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 green = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          green_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 blue = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          blue_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RGB::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bmp_grapher_proto.RGB)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 red = 1;
  if (this->red() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_red(), target);
  }

  // int32 green = 2;
  if (this->green() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_green(), target);
  }

  // int32 blue = 3;
  if (this->blue() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_blue(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bmp_grapher_proto.RGB)
  return target;
}

size_t RGB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bmp_grapher_proto.RGB)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 red = 1;
  if (this->red() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_red());
  }

  // int32 green = 2;
  if (this->green() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_green());
  }

  // int32 blue = 3;
  if (this->blue() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_blue());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RGB::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bmp_grapher_proto.RGB)
  GOOGLE_DCHECK_NE(&from, this);
  const RGB* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RGB>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bmp_grapher_proto.RGB)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bmp_grapher_proto.RGB)
    MergeFrom(*source);
  }
}

void RGB::MergeFrom(const RGB& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bmp_grapher_proto.RGB)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.red() != 0) {
    _internal_set_red(from._internal_red());
  }
  if (from.green() != 0) {
    _internal_set_green(from._internal_green());
  }
  if (from.blue() != 0) {
    _internal_set_blue(from._internal_blue());
  }
}

void RGB::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bmp_grapher_proto.RGB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RGB::CopyFrom(const RGB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bmp_grapher_proto.RGB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RGB::IsInitialized() const {
  return true;
}

void RGB::InternalSwap(RGB* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(red_, other->red_);
  swap(green_, other->green_);
  swap(blue_, other->blue_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RGB::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::InitAsDefaultInstance() {
  ::bmp_grapher_proto::_MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs_default_instance_._instance.get_mutable()->mandelbrot_color_ = const_cast< ::bmp_grapher_proto::RGB*>(
      ::bmp_grapher_proto::RGB::internal_default_instance());
  ::bmp_grapher_proto::_MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs_default_instance_._instance.get_mutable()->base_color_ = const_cast< ::bmp_grapher_proto::RGB*>(
      ::bmp_grapher_proto::RGB::internal_default_instance());
}
class MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::_Internal {
 public:
  static const ::bmp_grapher_proto::RGB& mandelbrot_color(const MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs* msg);
  static const ::bmp_grapher_proto::RGB& base_color(const MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs* msg);
};

const ::bmp_grapher_proto::RGB&
MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::_Internal::mandelbrot_color(const MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs* msg) {
  return *msg->mandelbrot_color_;
}
const ::bmp_grapher_proto::RGB&
MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::_Internal::base_color(const MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs* msg) {
  return *msg->base_color_;
}
MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.SingleColorSchemeArgs)
}
MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs(const MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._internal_has_mandelbrot_color()) {
    mandelbrot_color_ = new ::bmp_grapher_proto::RGB(*from.mandelbrot_color_);
  } else {
    mandelbrot_color_ = nullptr;
  }
  if (from._internal_has_base_color()) {
    base_color_ = new ::bmp_grapher_proto::RGB(*from.base_color_);
  } else {
    base_color_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.SingleColorSchemeArgs)
}

void MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs_bmp_5fgrapher_2eproto.base);
  ::memset(&mandelbrot_color_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&base_color_) -
      reinterpret_cast<char*>(&mandelbrot_color_)) + sizeof(base_color_));
}

MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::~MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs() {
  // @@protoc_insertion_point(destructor:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.SingleColorSchemeArgs)
  SharedDtor();
}

void MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::SharedDtor() {
  if (this != internal_default_instance()) delete mandelbrot_color_;
  if (this != internal_default_instance()) delete base_color_;
}

void MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs& MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs_bmp_5fgrapher_2eproto.base);
  return *internal_default_instance();
}


void MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::Clear() {
// @@protoc_insertion_point(message_clear_start:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.SingleColorSchemeArgs)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == nullptr && mandelbrot_color_ != nullptr) {
    delete mandelbrot_color_;
  }
  mandelbrot_color_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && base_color_ != nullptr) {
    delete base_color_;
  }
  base_color_ = nullptr;
  _internal_metadata_.Clear();
}

const char* MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .bmp_grapher_proto.RGB mandelbrot_color = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_mandelbrot_color(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .bmp_grapher_proto.RGB base_color = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_base_color(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.SingleColorSchemeArgs)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .bmp_grapher_proto.RGB mandelbrot_color = 1;
  if (this->has_mandelbrot_color()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::mandelbrot_color(this), target, stream);
  }

  // .bmp_grapher_proto.RGB base_color = 2;
  if (this->has_base_color()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::base_color(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.SingleColorSchemeArgs)
  return target;
}

size_t MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.SingleColorSchemeArgs)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .bmp_grapher_proto.RGB mandelbrot_color = 1;
  if (this->has_mandelbrot_color()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *mandelbrot_color_);
  }

  // .bmp_grapher_proto.RGB base_color = 2;
  if (this->has_base_color()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *base_color_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.SingleColorSchemeArgs)
  GOOGLE_DCHECK_NE(&from, this);
  const MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.SingleColorSchemeArgs)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.SingleColorSchemeArgs)
    MergeFrom(*source);
  }
}

void MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::MergeFrom(const MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.SingleColorSchemeArgs)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_mandelbrot_color()) {
    _internal_mutable_mandelbrot_color()->::bmp_grapher_proto::RGB::MergeFrom(from._internal_mandelbrot_color());
  }
  if (from.has_base_color()) {
    _internal_mutable_base_color()->::bmp_grapher_proto::RGB::MergeFrom(from._internal_base_color());
  }
}

void MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.SingleColorSchemeArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::CopyFrom(const MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.SingleColorSchemeArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::IsInitialized() const {
  return true;
}

void MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::InternalSwap(MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(mandelbrot_color_, other->mandelbrot_color_);
  swap(base_color_, other->base_color_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void MandelbrotConfig_MandelbrotRunArgs::InitAsDefaultInstance() {
  ::bmp_grapher_proto::_MandelbrotConfig_MandelbrotRunArgs_default_instance_.single_color_scheme_args_ = const_cast< ::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs*>(
      ::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::internal_default_instance());
}
class MandelbrotConfig_MandelbrotRunArgs::_Internal {
 public:
  static const ::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs& single_color_scheme_args(const MandelbrotConfig_MandelbrotRunArgs* msg);
};

const ::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs&
MandelbrotConfig_MandelbrotRunArgs::_Internal::single_color_scheme_args(const MandelbrotConfig_MandelbrotRunArgs* msg) {
  return *msg->color_scheme_args_.single_color_scheme_args_;
}
void MandelbrotConfig_MandelbrotRunArgs::set_allocated_single_color_scheme_args(::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs* single_color_scheme_args) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  clear_color_scheme_args();
  if (single_color_scheme_args) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      single_color_scheme_args = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, single_color_scheme_args, submessage_arena);
    }
    set_has_single_color_scheme_args();
    color_scheme_args_.single_color_scheme_args_ = single_color_scheme_args;
  }
  // @@protoc_insertion_point(field_set_allocated:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.single_color_scheme_args)
}
MandelbrotConfig_MandelbrotRunArgs::MandelbrotConfig_MandelbrotRunArgs()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs)
}
MandelbrotConfig_MandelbrotRunArgs::MandelbrotConfig_MandelbrotRunArgs(const MandelbrotConfig_MandelbrotRunArgs& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  out_filename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_out_filename().empty()) {
    out_filename_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.out_filename_);
  }
  color_scheme_ = from.color_scheme_;
  clear_has_color_scheme_args();
  switch (from.color_scheme_args_case()) {
    case kSingleColorSchemeArgs: {
      _internal_mutable_single_color_scheme_args()->::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::MergeFrom(from._internal_single_color_scheme_args());
      break;
    }
    case COLOR_SCHEME_ARGS_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs)
}

void MandelbrotConfig_MandelbrotRunArgs::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MandelbrotConfig_MandelbrotRunArgs_bmp_5fgrapher_2eproto.base);
  out_filename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  color_scheme_ = 0;
  clear_has_color_scheme_args();
}

MandelbrotConfig_MandelbrotRunArgs::~MandelbrotConfig_MandelbrotRunArgs() {
  // @@protoc_insertion_point(destructor:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs)
  SharedDtor();
}

void MandelbrotConfig_MandelbrotRunArgs::SharedDtor() {
  out_filename_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (has_color_scheme_args()) {
    clear_color_scheme_args();
  }
}

void MandelbrotConfig_MandelbrotRunArgs::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MandelbrotConfig_MandelbrotRunArgs& MandelbrotConfig_MandelbrotRunArgs::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MandelbrotConfig_MandelbrotRunArgs_bmp_5fgrapher_2eproto.base);
  return *internal_default_instance();
}


void MandelbrotConfig_MandelbrotRunArgs::clear_color_scheme_args() {
// @@protoc_insertion_point(one_of_clear_start:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs)
  switch (color_scheme_args_case()) {
    case kSingleColorSchemeArgs: {
      delete color_scheme_args_.single_color_scheme_args_;
      break;
    }
    case COLOR_SCHEME_ARGS_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = COLOR_SCHEME_ARGS_NOT_SET;
}


void MandelbrotConfig_MandelbrotRunArgs::Clear() {
// @@protoc_insertion_point(message_clear_start:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  out_filename_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  color_scheme_ = 0;
  clear_color_scheme_args();
  _internal_metadata_.Clear();
}

const char* MandelbrotConfig_MandelbrotRunArgs::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string out_filename = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_out_filename();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.out_filename"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.MandelbrotColorScheme color_scheme = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_color_scheme(static_cast<::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_MandelbrotColorScheme>(val));
        } else goto handle_unusual;
        continue;
      // .bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.SingleColorSchemeArgs single_color_scheme_args = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_single_color_scheme_args(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MandelbrotConfig_MandelbrotRunArgs::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string out_filename = 1;
  if (this->out_filename().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_out_filename().data(), static_cast<int>(this->_internal_out_filename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.out_filename");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_out_filename(), target);
  }

  // .bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.MandelbrotColorScheme color_scheme = 2;
  if (this->color_scheme() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_color_scheme(), target);
  }

  // .bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.SingleColorSchemeArgs single_color_scheme_args = 3;
  if (_internal_has_single_color_scheme_args()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::single_color_scheme_args(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs)
  return target;
}

size_t MandelbrotConfig_MandelbrotRunArgs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string out_filename = 1;
  if (this->out_filename().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_out_filename());
  }

  // .bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.MandelbrotColorScheme color_scheme = 2;
  if (this->color_scheme() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_color_scheme());
  }

  switch (color_scheme_args_case()) {
    // .bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs.SingleColorSchemeArgs single_color_scheme_args = 3;
    case kSingleColorSchemeArgs: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *color_scheme_args_.single_color_scheme_args_);
      break;
    }
    case COLOR_SCHEME_ARGS_NOT_SET: {
      break;
    }
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MandelbrotConfig_MandelbrotRunArgs::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs)
  GOOGLE_DCHECK_NE(&from, this);
  const MandelbrotConfig_MandelbrotRunArgs* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MandelbrotConfig_MandelbrotRunArgs>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs)
    MergeFrom(*source);
  }
}

void MandelbrotConfig_MandelbrotRunArgs::MergeFrom(const MandelbrotConfig_MandelbrotRunArgs& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.out_filename().size() > 0) {

    out_filename_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.out_filename_);
  }
  if (from.color_scheme() != 0) {
    _internal_set_color_scheme(from._internal_color_scheme());
  }
  switch (from.color_scheme_args_case()) {
    case kSingleColorSchemeArgs: {
      _internal_mutable_single_color_scheme_args()->::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs::MergeFrom(from._internal_single_color_scheme_args());
      break;
    }
    case COLOR_SCHEME_ARGS_NOT_SET: {
      break;
    }
  }
}

void MandelbrotConfig_MandelbrotRunArgs::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MandelbrotConfig_MandelbrotRunArgs::CopyFrom(const MandelbrotConfig_MandelbrotRunArgs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MandelbrotConfig_MandelbrotRunArgs::IsInitialized() const {
  return true;
}

void MandelbrotConfig_MandelbrotRunArgs::InternalSwap(MandelbrotConfig_MandelbrotRunArgs* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  out_filename_.Swap(&other->out_filename_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(color_scheme_, other->color_scheme_);
  swap(color_scheme_args_, other->color_scheme_args_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata MandelbrotConfig_MandelbrotRunArgs::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void MandelbrotConfig::InitAsDefaultInstance() {
}
class MandelbrotConfig::_Internal {
 public:
};

MandelbrotConfig::MandelbrotConfig()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bmp_grapher_proto.MandelbrotConfig)
}
MandelbrotConfig::MandelbrotConfig(const MandelbrotConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      run_args_(from.run_args_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  max_iterations_ = from.max_iterations_;
  // @@protoc_insertion_point(copy_constructor:bmp_grapher_proto.MandelbrotConfig)
}

void MandelbrotConfig::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MandelbrotConfig_bmp_5fgrapher_2eproto.base);
  max_iterations_ = 0;
}

MandelbrotConfig::~MandelbrotConfig() {
  // @@protoc_insertion_point(destructor:bmp_grapher_proto.MandelbrotConfig)
  SharedDtor();
}

void MandelbrotConfig::SharedDtor() {
}

void MandelbrotConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MandelbrotConfig& MandelbrotConfig::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MandelbrotConfig_bmp_5fgrapher_2eproto.base);
  return *internal_default_instance();
}


void MandelbrotConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:bmp_grapher_proto.MandelbrotConfig)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  run_args_.Clear();
  max_iterations_ = 0;
  _internal_metadata_.Clear();
}

const char* MandelbrotConfig::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 max_iterations = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          max_iterations_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs run_args = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_run_args(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MandelbrotConfig::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bmp_grapher_proto.MandelbrotConfig)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 max_iterations = 1;
  if (this->max_iterations() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_max_iterations(), target);
  }

  // repeated .bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs run_args = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_run_args_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_run_args(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bmp_grapher_proto.MandelbrotConfig)
  return target;
}

size_t MandelbrotConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bmp_grapher_proto.MandelbrotConfig)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .bmp_grapher_proto.MandelbrotConfig.MandelbrotRunArgs run_args = 2;
  total_size += 1UL * this->_internal_run_args_size();
  for (const auto& msg : this->run_args_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int32 max_iterations = 1;
  if (this->max_iterations() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_max_iterations());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MandelbrotConfig::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bmp_grapher_proto.MandelbrotConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const MandelbrotConfig* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MandelbrotConfig>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bmp_grapher_proto.MandelbrotConfig)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bmp_grapher_proto.MandelbrotConfig)
    MergeFrom(*source);
  }
}

void MandelbrotConfig::MergeFrom(const MandelbrotConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bmp_grapher_proto.MandelbrotConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  run_args_.MergeFrom(from.run_args_);
  if (from.max_iterations() != 0) {
    _internal_set_max_iterations(from._internal_max_iterations());
  }
}

void MandelbrotConfig::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bmp_grapher_proto.MandelbrotConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MandelbrotConfig::CopyFrom(const MandelbrotConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bmp_grapher_proto.MandelbrotConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MandelbrotConfig::IsInitialized() const {
  return true;
}

void MandelbrotConfig::InternalSwap(MandelbrotConfig* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  run_args_.InternalSwap(&other->run_args_);
  swap(max_iterations_, other->max_iterations_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MandelbrotConfig::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void BmpGrapher::InitAsDefaultInstance() {
  ::bmp_grapher_proto::_BmpGrapher_default_instance_.mandelbrot_config_ = const_cast< ::bmp_grapher_proto::MandelbrotConfig*>(
      ::bmp_grapher_proto::MandelbrotConfig::internal_default_instance());
}
class BmpGrapher::_Internal {
 public:
  static const ::bmp_grapher_proto::MandelbrotConfig& mandelbrot_config(const BmpGrapher* msg);
};

const ::bmp_grapher_proto::MandelbrotConfig&
BmpGrapher::_Internal::mandelbrot_config(const BmpGrapher* msg) {
  return *msg->bmp_grapher_config_.mandelbrot_config_;
}
void BmpGrapher::set_allocated_mandelbrot_config(::bmp_grapher_proto::MandelbrotConfig* mandelbrot_config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  clear_bmp_grapher_config();
  if (mandelbrot_config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      mandelbrot_config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, mandelbrot_config, submessage_arena);
    }
    set_has_mandelbrot_config();
    bmp_grapher_config_.mandelbrot_config_ = mandelbrot_config;
  }
  // @@protoc_insertion_point(field_set_allocated:bmp_grapher_proto.BmpGrapher.mandelbrot_config)
}
BmpGrapher::BmpGrapher()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bmp_grapher_proto.BmpGrapher)
}
BmpGrapher::BmpGrapher(const BmpGrapher& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_center_, &from.x_center_,
    static_cast<size_t>(reinterpret_cast<char*>(&pixel_height_) -
    reinterpret_cast<char*>(&x_center_)) + sizeof(pixel_height_));
  clear_has_bmp_grapher_config();
  switch (from.bmp_grapher_config_case()) {
    case kMandelbrotConfig: {
      _internal_mutable_mandelbrot_config()->::bmp_grapher_proto::MandelbrotConfig::MergeFrom(from._internal_mandelbrot_config());
      break;
    }
    case BMP_GRAPHER_CONFIG_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:bmp_grapher_proto.BmpGrapher)
}

void BmpGrapher::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_BmpGrapher_bmp_5fgrapher_2eproto.base);
  ::memset(&x_center_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&pixel_height_) -
      reinterpret_cast<char*>(&x_center_)) + sizeof(pixel_height_));
  clear_has_bmp_grapher_config();
}

BmpGrapher::~BmpGrapher() {
  // @@protoc_insertion_point(destructor:bmp_grapher_proto.BmpGrapher)
  SharedDtor();
}

void BmpGrapher::SharedDtor() {
  if (has_bmp_grapher_config()) {
    clear_bmp_grapher_config();
  }
}

void BmpGrapher::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const BmpGrapher& BmpGrapher::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_BmpGrapher_bmp_5fgrapher_2eproto.base);
  return *internal_default_instance();
}


void BmpGrapher::clear_bmp_grapher_config() {
// @@protoc_insertion_point(one_of_clear_start:bmp_grapher_proto.BmpGrapher)
  switch (bmp_grapher_config_case()) {
    case kMandelbrotConfig: {
      delete bmp_grapher_config_.mandelbrot_config_;
      break;
    }
    case BMP_GRAPHER_CONFIG_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = BMP_GRAPHER_CONFIG_NOT_SET;
}


void BmpGrapher::Clear() {
// @@protoc_insertion_point(message_clear_start:bmp_grapher_proto.BmpGrapher)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_center_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&pixel_height_) -
      reinterpret_cast<char*>(&x_center_)) + sizeof(pixel_height_));
  clear_bmp_grapher_config();
  _internal_metadata_.Clear();
}

const char* BmpGrapher::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // double x_center = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          x_center_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double y_center = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17)) {
          y_center_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double x_domain_width = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 25)) {
          x_domain_width_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // int32 pixel_width = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          pixel_width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 pixel_height = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          pixel_height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .bmp_grapher_proto.MandelbrotConfig mandelbrot_config = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_mandelbrot_config(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* BmpGrapher::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bmp_grapher_proto.BmpGrapher)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double x_center = 1;
  if (!(this->x_center() <= 0 && this->x_center() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->_internal_x_center(), target);
  }

  // double y_center = 2;
  if (!(this->y_center() <= 0 && this->y_center() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(2, this->_internal_y_center(), target);
  }

  // double x_domain_width = 3;
  if (!(this->x_domain_width() <= 0 && this->x_domain_width() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(3, this->_internal_x_domain_width(), target);
  }

  // int32 pixel_width = 4;
  if (this->pixel_width() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_pixel_width(), target);
  }

  // int32 pixel_height = 5;
  if (this->pixel_height() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(5, this->_internal_pixel_height(), target);
  }

  // .bmp_grapher_proto.MandelbrotConfig mandelbrot_config = 6;
  if (_internal_has_mandelbrot_config()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        6, _Internal::mandelbrot_config(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bmp_grapher_proto.BmpGrapher)
  return target;
}

size_t BmpGrapher::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bmp_grapher_proto.BmpGrapher)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double x_center = 1;
  if (!(this->x_center() <= 0 && this->x_center() >= 0)) {
    total_size += 1 + 8;
  }

  // double y_center = 2;
  if (!(this->y_center() <= 0 && this->y_center() >= 0)) {
    total_size += 1 + 8;
  }

  // double x_domain_width = 3;
  if (!(this->x_domain_width() <= 0 && this->x_domain_width() >= 0)) {
    total_size += 1 + 8;
  }

  // int32 pixel_width = 4;
  if (this->pixel_width() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_pixel_width());
  }

  // int32 pixel_height = 5;
  if (this->pixel_height() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_pixel_height());
  }

  switch (bmp_grapher_config_case()) {
    // .bmp_grapher_proto.MandelbrotConfig mandelbrot_config = 6;
    case kMandelbrotConfig: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *bmp_grapher_config_.mandelbrot_config_);
      break;
    }
    case BMP_GRAPHER_CONFIG_NOT_SET: {
      break;
    }
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BmpGrapher::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bmp_grapher_proto.BmpGrapher)
  GOOGLE_DCHECK_NE(&from, this);
  const BmpGrapher* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<BmpGrapher>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bmp_grapher_proto.BmpGrapher)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bmp_grapher_proto.BmpGrapher)
    MergeFrom(*source);
  }
}

void BmpGrapher::MergeFrom(const BmpGrapher& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bmp_grapher_proto.BmpGrapher)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.x_center() <= 0 && from.x_center() >= 0)) {
    _internal_set_x_center(from._internal_x_center());
  }
  if (!(from.y_center() <= 0 && from.y_center() >= 0)) {
    _internal_set_y_center(from._internal_y_center());
  }
  if (!(from.x_domain_width() <= 0 && from.x_domain_width() >= 0)) {
    _internal_set_x_domain_width(from._internal_x_domain_width());
  }
  if (from.pixel_width() != 0) {
    _internal_set_pixel_width(from._internal_pixel_width());
  }
  if (from.pixel_height() != 0) {
    _internal_set_pixel_height(from._internal_pixel_height());
  }
  switch (from.bmp_grapher_config_case()) {
    case kMandelbrotConfig: {
      _internal_mutable_mandelbrot_config()->::bmp_grapher_proto::MandelbrotConfig::MergeFrom(from._internal_mandelbrot_config());
      break;
    }
    case BMP_GRAPHER_CONFIG_NOT_SET: {
      break;
    }
  }
}

void BmpGrapher::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bmp_grapher_proto.BmpGrapher)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BmpGrapher::CopyFrom(const BmpGrapher& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bmp_grapher_proto.BmpGrapher)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BmpGrapher::IsInitialized() const {
  return true;
}

void BmpGrapher::InternalSwap(BmpGrapher* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(x_center_, other->x_center_);
  swap(y_center_, other->y_center_);
  swap(x_domain_width_, other->x_domain_width_);
  swap(pixel_width_, other->pixel_width_);
  swap(pixel_height_, other->pixel_height_);
  swap(bmp_grapher_config_, other->bmp_grapher_config_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata BmpGrapher::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void BmpGrapherFactory::InitAsDefaultInstance() {
}
class BmpGrapherFactory::_Internal {
 public:
};

BmpGrapherFactory::BmpGrapherFactory()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bmp_grapher_proto.BmpGrapherFactory)
}
BmpGrapherFactory::BmpGrapherFactory(const BmpGrapherFactory& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      bitmaps_(from.bitmaps_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:bmp_grapher_proto.BmpGrapherFactory)
}

void BmpGrapherFactory::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_BmpGrapherFactory_bmp_5fgrapher_2eproto.base);
}

BmpGrapherFactory::~BmpGrapherFactory() {
  // @@protoc_insertion_point(destructor:bmp_grapher_proto.BmpGrapherFactory)
  SharedDtor();
}

void BmpGrapherFactory::SharedDtor() {
}

void BmpGrapherFactory::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const BmpGrapherFactory& BmpGrapherFactory::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_BmpGrapherFactory_bmp_5fgrapher_2eproto.base);
  return *internal_default_instance();
}


void BmpGrapherFactory::Clear() {
// @@protoc_insertion_point(message_clear_start:bmp_grapher_proto.BmpGrapherFactory)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  bitmaps_.Clear();
  _internal_metadata_.Clear();
}

const char* BmpGrapherFactory::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .bmp_grapher_proto.BmpGrapher bitmaps = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_bitmaps(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* BmpGrapherFactory::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bmp_grapher_proto.BmpGrapherFactory)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .bmp_grapher_proto.BmpGrapher bitmaps = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_bitmaps_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_bitmaps(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bmp_grapher_proto.BmpGrapherFactory)
  return target;
}

size_t BmpGrapherFactory::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bmp_grapher_proto.BmpGrapherFactory)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .bmp_grapher_proto.BmpGrapher bitmaps = 1;
  total_size += 1UL * this->_internal_bitmaps_size();
  for (const auto& msg : this->bitmaps_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BmpGrapherFactory::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bmp_grapher_proto.BmpGrapherFactory)
  GOOGLE_DCHECK_NE(&from, this);
  const BmpGrapherFactory* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<BmpGrapherFactory>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bmp_grapher_proto.BmpGrapherFactory)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bmp_grapher_proto.BmpGrapherFactory)
    MergeFrom(*source);
  }
}

void BmpGrapherFactory::MergeFrom(const BmpGrapherFactory& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bmp_grapher_proto.BmpGrapherFactory)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  bitmaps_.MergeFrom(from.bitmaps_);
}

void BmpGrapherFactory::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bmp_grapher_proto.BmpGrapherFactory)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BmpGrapherFactory::CopyFrom(const BmpGrapherFactory& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bmp_grapher_proto.BmpGrapherFactory)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BmpGrapherFactory::IsInitialized() const {
  return true;
}

void BmpGrapherFactory::InternalSwap(BmpGrapherFactory* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  bitmaps_.InternalSwap(&other->bitmaps_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BmpGrapherFactory::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace bmp_grapher_proto
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::bmp_grapher_proto::RGB* Arena::CreateMaybeMessage< ::bmp_grapher_proto::RGB >(Arena* arena) {
  return Arena::CreateInternal< ::bmp_grapher_proto::RGB >(arena);
}
template<> PROTOBUF_NOINLINE ::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs* Arena::CreateMaybeMessage< ::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs >(Arena* arena) {
  return Arena::CreateInternal< ::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs_SingleColorSchemeArgs >(arena);
}
template<> PROTOBUF_NOINLINE ::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs* Arena::CreateMaybeMessage< ::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs >(Arena* arena) {
  return Arena::CreateInternal< ::bmp_grapher_proto::MandelbrotConfig_MandelbrotRunArgs >(arena);
}
template<> PROTOBUF_NOINLINE ::bmp_grapher_proto::MandelbrotConfig* Arena::CreateMaybeMessage< ::bmp_grapher_proto::MandelbrotConfig >(Arena* arena) {
  return Arena::CreateInternal< ::bmp_grapher_proto::MandelbrotConfig >(arena);
}
template<> PROTOBUF_NOINLINE ::bmp_grapher_proto::BmpGrapher* Arena::CreateMaybeMessage< ::bmp_grapher_proto::BmpGrapher >(Arena* arena) {
  return Arena::CreateInternal< ::bmp_grapher_proto::BmpGrapher >(arena);
}
template<> PROTOBUF_NOINLINE ::bmp_grapher_proto::BmpGrapherFactory* Arena::CreateMaybeMessage< ::bmp_grapher_proto::BmpGrapherFactory >(Arena* arena) {
  return Arena::CreateInternal< ::bmp_grapher_proto::BmpGrapherFactory >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
